# Nome do nosso fluxo de trabalho, que aparecer谩 no GitHub
name: CI/CD VETLAB

# Define quando este fluxo de trabalho deve ser acionado
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # O tipo de m谩quina que o rob么 usar谩
    runs-on: ubuntu-latest

    # Os passos que ser茫o executados em sequ锚ncia
    steps:
      # 1. Baixa o seu c贸digo para a m谩quina do rob么
      - name: Clonar reposit贸rio
        uses: actions/checkout@v3

      # 2. Configura o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Instala todas as depend锚ncias do seu projeto
      - name: Instalar depend锚ncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Roda os testes do Django
      - name: Rodar testes
        # Aqui n贸s fornecemos a chave secreta que o rob么 precisa para rodar os testes
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY_FOR_TESTS }}
        run: |
          python manage.py test

      # 5. Passo de Deploy: s贸 executa se o 'push' for na branch 'main' e os testes passarem
      - name:  Deploy autom谩tico no Render
        if: github.ref == 'refs/heads/main' && success()
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
